name: build
on: 
  schedule:
    - cron: "*/2 * * * *"
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'suriyancss/azure-test:latest'
          format: 'table'
#          output: 'trivy-results.sarif'
        env:
          TRIVY_USERNAME: 'suriyancss'
          TRIVY_PASSWORD: 'welcome@123'

#      - name: Upload Trivy scan results to GitHub Security tab
#        uses: github/codeql-action/upload-sarif@v2
#        with:
#          sarif_file: 'trivy-results.sarif'
