name: build
on: 
  push:
    branches:
      - "main"
#  schedule:
#    - cron: "*/1 * * * *"
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'suriyancss/azure-test:ubuntu18'
          format: 'sarif'
          exit-code: '1'
          output: 'trivy-results.sarif'
        env:
          TRIVY_USERNAME: 'suriyancss'
          TRIVY_PASSWORD: 'welcome@123'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Upload file to container
        if: failure()
        uses: LanceMcCarthy/Action-AzureBlobUpload@v2
        with:
          connection_string: DefaultEndpointsProtocol=https;AccountName=st4devops4eus;AccountKey=xr6EnxFB1jQ+Z5FEfDy3frI6N79URs/J9EwOZQ/pKpCbLhzMIqE2RjCngn4HlnBYrxztAh+4qCJO+ASt2tlM1A==;EndpointSuffix=core.windows.net
          container_name: fileuploadtest-suriyan #(input container name)
          source_folder: trivy-results.sarif
          destination_folder: scanresultappname/scanresultsregistry #(input folder)
          delete_if_exists: true
