name: build
on: 
  push:
    branches:
      - main
#  schedule:
#    - cron: "*/2 * * * *"
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3

      # scanning the image using trivy
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'suriyancss/azure-test:ubuntu18'
          format: 'table'
          exit-code: '1'
          output: 'trivy-results.sarif'
        env:
          TRIVY_USERNAME: 'suriyancss'
          TRIVY_PASSWORD: 'welcome@123'
          
#      - name: Upload Trivy scan results to GitHub Security
#        uses: github/codeql-action/upload-sarif@v2
#        with:
#          sarif_file: 'trivy-results.sarif'
      # uploading output file to storage container
      - name: Upload file to container
        uses: LanceMcCarthy/Action-AzureBlobUpload@v2
        with:
          connection_string: DefaultEndpointsProtocol=https;AccountName=teststroragesuriyan123;AccountKey=jJw40Ppv6EyKDqF0PsoL+R+b3IhjnHAwB5VOrPh4zqNVLQf1Hu/cvafopw+ZLkPu8tIbIZQxb2IM+ASt13QVsQ==;EndpointSuffix=core.windows.net
          container_name: testcontainer123
          source_folder: trivy-results.sarif
          destination_folder: scanresults123
          delete_if_exists: true
      
